name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install clang-tidy
        run: sudo apt install clang-tidy
        
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.5.3
        with:
          version: "10.0"
      
      - name: Get latest ninja
        uses: urkle/action-get-ninja@v1

      - name: Build application
        run: ./build.sh